import 'package:applicate/core/app_export.dart';

class StringConstants {
  static List<Group> listOfGroups = [
    //Group(name: '----------1 КУРС----------', type: "divider"),
    Group(name: 'МБС-301-О-01', countOfSubgroups: 2),
    Group(name: 'МБС-302-О-01', countOfSubgroups: 2),
    Group(name: 'МИБ-301-О-02', countOfSubgroups: 2),
    Group(name: 'ММБ-301-О-04', countOfSubgroups: 2),
    Group(name: 'ММБ-302-О-04', countOfSubgroups: 2),
    Group(name: 'ММБ-303-О-04', countOfSubgroups: 2),
    Group(name: 'МПБ-301-О-01', countOfSubgroups: 2),
    Group(name: 'МФС-301-О-02', countOfSubgroups: 1),
    Group(name: 'МММ-301-О-06', countOfSubgroups: 1),

    //Group(name: '----------2 КУРС----------', type: "divider"),
    Group(name: 'МББ-201-О-01', countOfSubgroups: 1),
    Group(name: 'МБС-201-О-01', countOfSubgroups: 2),
    Group(name: 'МБС-202-О-01', countOfSubgroups: 2),
    Group(name: 'МИБ-201-О-01', countOfSubgroups: 2),
    Group(name: 'ММБ-201-О-04', countOfSubgroups: 2),
    Group(name: 'ММБ-202-О-04', countOfSubgroups: 2),
    Group(name: 'ММБ-203-О-04', countOfSubgroups: 2),
    Group(name: 'МПБ-201-О-01', countOfSubgroups: 2),
    Group(name: 'МИМ-201-О-01', countOfSubgroups: 1),
    Group(name: 'МММ-201-О-01', countOfSubgroups: 1),

    //Group(name: '----------3 КУРС----------', type: "divider"),
    Group(name: 'МББ-101-О-01', countOfSubgroups: 2),
    Group(name: 'МБС-101-О-01', countOfSubgroups: 3),
    Group(name: 'МКБ-101-О-01', countOfSubgroups: 2),
    Group(name: 'МИБ-101-О-01', countOfSubgroups: 2),
    Group(name: 'ММБ-102-О-01', countOfSubgroups: 2),
    Group(name: 'ММБ-103-О-02', countOfSubgroups: 2),
    Group(name: 'ММБ-104-О-02', countOfSubgroups: 2),
    Group(name: 'МПБ-101-О-01', countOfSubgroups: 2),
    Group(name: 'МФС-101-О-01', countOfSubgroups: 1),

    //Group(name: '----------4 КУРС----------', type: "divider"),
    Group(name: 'МББ-001-О-01', countOfSubgroups: 1),
    Group(name: 'МБС-001-О-01', countOfSubgroups: 3),
    Group(name: 'МИБ-001-О-01', countOfSubgroups: 2),
    Group(name: 'МКБ-001-О-01', countOfSubgroups: 1),
    Group(name: 'ММБ-002-О-01', countOfSubgroups: 2),
    Group(name: 'ММБ-003-О-01', countOfSubgroups: 2),
    Group(name: 'ММБ-004-О-02', countOfSubgroups: 3),
    Group(name: 'МПБ-001-О-01', countOfSubgroups: 2),
    Group(name: 'МФС-001-О-01', countOfSubgroups: 1),
    
    //Group(name: '----------5 КУРС----------', type: "divider"),
    Group(name: 'МБС-901-О-01', countOfSubgroups: 2),
    Group(name: 'МФС-901-О-01', countOfSubgroups: 1),
    Group(name: 'МБС-801-О-01', countOfSubgroups: 1),
    //Group(name: '--------Магистратура------', type: "divider"),
    Group(name: 'МИМ-201-О-01', countOfSubgroups: 0),
  ];

  static Map<String, String> listOfCodeGroups = {
    //    ---1 КУРС---
    'МБС-301-О-01': "5028",
    'МБС-302-О-01': "5030",
    'МИБ-301-О-02': "5031",
    'ММБ-301-О-04': "5018",
    'ММБ-302-О-04': "5020",
    'ММБ-303-О-04': "5002",
    'МПБ-301-О-01': "5029",
    'МФС-301-О-02': "5015",
    'МММ-301-О-06': "3641",

    //    ---2 КУРС---
    'МББ-201-О-01': "2592",
    'МБС-201-О-01': "2608",
    'МБС-202-О-01': "2629",
    'МИБ-201-О-01': "2620",
    'ММБ-201-О-04': "1163",
    'ММБ-202-О-04': "1154",
    'ММБ-203-О-04': "1177",
    'МПБ-201-О-01': "2624",
    'МММ-201-О-01': "3641",

    //    ---3 КУРС---
    'МББ-101-О-01': "2618",
    'МБС-101-О-01': "2606",
    'МКБ-101-О-01': "2604",
    'МИБ-101-О-01': "2623",
    'ММБ-102-О-01': "1184",
    'ММБ-103-О-02': "1145",
    'ММБ-104-О-02': "1189",
    'МПБ-101-О-01': "2638",
    'МФС-101-О-01': "1172",

    //    ---4 КУРС---
    'МББ-001-О-01': "2600",
    'МБС-001-О-01': "2595",
    'МИБ-001-О-01': "2617",
    'МКБ-001-О-01': "2645",
    'ММБ-002-О-01': "1148",
    'ММБ-003-О-01': "1176",
    'ММБ-004-О-02': "1181",
    'МПБ-001-О-01': "2612",
    'МФС-001-О-01': "1160",

    //    ---5 КУРС---
    'МБС-901-О-01': "2590",
    'МБС-801-О-01': "2668",
    'МФС-901-О-01': "1142",

    // Магистратура
    'МИМ-201-О-01': "3802",
  };

  static Map<String, List<Items>> listOfItemsGroups = {
    //               --- 1 КУРС ---
    'МБС-301-О-01': ListOfItems.listOfItemsOfMBS20X,
    'МБС-302-О-01': ListOfItems.listOfItemsOfMBS20X,
    'МИБ-301-О-02': ListOfItems.listOfItemsOfMIB201,
    'ММБ-301-О-04': ListOfItems.listOfItemsOfMMB20X,
    'ММБ-302-О-04': ListOfItems.listOfItemsOfMMB20X,
    'ММБ-303-О-04': ListOfItems.listOfItemsOfMMB20X,
    'МПБ-301-О-01': ListOfItems.listOfItemsOfMPB201,
    'МФС-301-О-02': ListOfItems.listOfItemsOfMFS301,
    'МММ-301-О-06': ListOfItems.listOfItemsOfMFS301,

    //               --- 2 КУРС ---
    'МББ-201-О-01': ListOfItems.listOfItemsOfMBB201,
    'МБС-201-О-01': ListOfItems.listOfItemsOfMBS20X,
    'МБС-202-О-01': ListOfItems.listOfItemsOfMBS20X,
    'МИБ-201-О-01': ListOfItems.listOfItemsOfMIB201,
    'ММБ-201-О-04': ListOfItems.listOfItemsOfMMB20X,
    'ММБ-202-О-04': ListOfItems.listOfItemsOfMMB20X,
    'ММБ-203-О-04': ListOfItems.listOfItemsOfMMB20X,
    'МПБ-201-О-01': ListOfItems.listOfItemsOfMPB201,
    'МММ-201-О-01': ListOfItems.listOfItemsOfMFS301,

    //               --- 3 КУРС ---
    'МББ-101-О-01': ListOfItems.listOfItemsOfMBB101,
    'МБС-101-О-01': ListOfItems.listOfItemsOfMBS10X,
    'МКБ-101-О-01': ListOfItems.listOfItemsOfMKB101,
    'МИБ-101-О-01': ListOfItems.listOfItemsOfMIB101,
    'ММБ-102-О-01': ListOfItems.listOfItemsOfMMB10X,
    'ММБ-103-О-02': ListOfItems.listOfItemsOfMMB10X,
    'ММБ-104-О-02': ListOfItems.listOfItemsOfMMB10X,
    'МПБ-101-О-01': ListOfItems.listOfItemsOfMPB101,
    'МФС-101-О-01': ListOfItems.listOfItemsOfMFS101,

    //               --- 4 КУРС ---
    'МББ-001-О-01': ListOfItems.listOfItemsOfMBB001,
    'МБС-001-О-01': ListOfItems.listOfItemsOfMBS00X,
    'МИБ-001-О-01': ListOfItems.listOfItemsOfMIB001,
    'МКБ-001-О-01': ListOfItems.listOfItemsOfMKB001,
    'ММБ-002-О-01': ListOfItems.listOfItemsOfMMB002,
    'ММБ-003-О-01': ListOfItems.listOfItemsOfMMB0034,
    'ММБ-004-О-02': ListOfItems.listOfItemsOfMMB0034,
    'МПБ-001-О-01': ListOfItems.listOfItemsOfMPB001,
    'МФС-001-О-01': ListOfItems.listOfItemsOfMFS001,

    //               --- 5 КУРС ---
    'МБС-901-О-01': ListOfItems.listOfItemsOfMBS901,
    'МБС-801-О-01': ListOfItems.listOfItemsOfMBS801,
    'МФС-901-О-01': ListOfItems.listOfItemsOfMFS901,

    //          --- МАГИСТРАТУРА ---
    'МИМ-201-О-01': ListOfItems.listOfItemsOfMIM,
  };

  static Map<String, List<String>> listOfStudentsGroups = {
    //                --- 1 КУРС ---
    'МБС-301-О-01': ListOfStudents.listOfStudentsOfMBS301,
    'МБС-302-О-01': ListOfStudents.listOfStudentsOfMBS302,
    'МИБ-301-О-02': ListOfStudents.listOfStudentsOfMIB301,
    'ММБ-301-О-04': ListOfStudents.listOfStudentsOfMMB301,
    'ММБ-302-О-04': ListOfStudents.listOfStudentsOfMMB302,
    'ММБ-303-О-04': ListOfStudents.listOfStudentsOfMMB303,
    'МПБ-301-О-01': ListOfStudents.listOfStudentsOfMPB301,
    'МФС-301-О-02': ListOfStudents.listOfStudentsOfMFS301,
    'МММ-301-О-06': ListOfStudents.listOfStudentsOfMMM301,

    //                --- 2 КУРС ---
    'МББ-201-О-01': ListOfStudents.listOfStudentsOfMBB201,
    'МБС-201-О-01': ListOfStudents.listOfStudentsOfMBS201,
    'МБС-202-О-01': ListOfStudents.listOfStudentsOfMBS202,
    'МИБ-201-О-01': ListOfStudents.listOfStudentsOfMIB201,
    'ММБ-201-О-04': ListOfStudents.listOfStudentsOfMMB201,
    'ММБ-202-О-04': ListOfStudents.listOfStudentsOfMMB202,
    'ММБ-203-О-04': ListOfStudents.listOfStudentsOfMMB203,
    'МПБ-201-О-01': ListOfStudents.listOfStudentsOfMPB201,
    'МММ-201-О-01': ListOfStudents.listOfStudentsOfMMM201,

    //                --- 3 КУРС ---
    'МББ-101-О-01': ListOfStudents.listOfStudentsOfMBB101,
    'МБС-101-О-01': ListOfStudents.listOfStudentsOfMBS101,
    'МКБ-101-О-01': ListOfStudents.listOfStudentsOfMKB101,
    'МИБ-101-О-01': ListOfStudents.listOfStudentsOfMIB101,
    'ММБ-102-О-01': ListOfStudents.listOfStudentsOfMMB102,
    'ММБ-103-О-02': ListOfStudents.listOfStudentsOfMMB103,
    'ММБ-104-О-02': ListOfStudents.listOfStudentsOfMMB104,
    'МПБ-101-О-01': ListOfStudents.listOfStudentsOfMPB101,
    'МФС-101-О-01': ListOfStudents.listOfStudentsOfMFS101,

    //                --- 4 КУРС ---
    'МББ-001-О-01': ListOfStudents.listOfStudentsOfMBB001,
    'МБС-001-О-01': ListOfStudents.listOfStudentsOfMBS001,
    'МИБ-001-О-01': ListOfStudents.listOfStudentsOfMIB001,
    'МКБ-001-О-01': ListOfStudents.listOfStudentsOfMKB001,
    'ММБ-002-О-01': ListOfStudents.listOfStudentsOfMMB002,
    'ММБ-003-О-01': ListOfStudents.listOfStudentsOfMMB003,
    'ММБ-004-О-02': ListOfStudents.listOfStudentsOfMMB004,
    'МПБ-001-О-01': ListOfStudents.listOfStudentsOfMPB001,
    'МФС-001-О-01': ListOfStudents.listOfStudentsOfMFS001,

    //                --- 5 КУРС ---
    'МБС-901-О-01': ListOfStudents.listOfStudentsOfMBS901,
    'МБС-801-О-01': ListOfStudents.listOfStudentsOfMBS801,
    'МФС-901-О-01': ListOfStudents.listOfStudentsOfMFS901,

    //             --- МАГИСТРАТУРА ---
    'МИМ-201-О-01': ListOfStudents.listOfStudentsOfMIM201,
  };

  static Map<String, String> listOfItems = {
    'Web-программирование': 'web-prog.png',
    'SMM-продвижение': 'smm.jpg',
    'Администрирование сетевых операционных систем': 'admin_seti.jpg',
    'Алгебра': 'alg.jpg',
    'Алгебра и геометрия': 'alg_and_geom.jpg',
    'Алгебра и теория чисел': 'alg.jpg',
    'Алгоритмизация и программирование': 'algoritm_prog.jpg',
    'Алгоритмы анализа данных и машинное обучение / Веб-программирование': 'web-prog.png',
    'Алгоритмы анализа изображений': 'isk_int.jpg',
    'Алгоритмы кодировки и сжатия': 'isk_int.jpg',
    'Алгоритмы спектрального анализа данных / Защита сетевого периметра': 'def_seti.jpg',
    'Анализ статистических данных': 'analiz.jpg',
    'Анализ уязвимостей компьютерных сетей': 'def_seti.jpg',
    'Анализ уязвимостей программного обеспечения': 'algoritm_prog.jpg',
    'Анализ уязвимостей программного обеспечения / Безопасность программного кода': 'algoritm_prog.jpg',
    'Аналитическая геометрия': 'anal_geom.jpg',
    'Аппаратные средства вычислительной техники': 'algoritm_prog.jpg',
    'Ассемблер': 'teor_vic.jpg',
    'Базы данных': 'DB.jpg',
    'Безопасность жизнедеятельности': 'BGD.jpg',
    'Бизнес-английский язык в IT': 'eng_it.jpg',
    'Биоинформатика': 'bio_inf.jpg',
    'Вариационное исчисление и оптимальное управление': 'var_isch.jpg',
    'Введение в прикладную математику': 'comp_anal.jpg',
    'Введение в программирование': 'prog.jpg',
    'Вредоносные программные средства': 'virus.jpg',
    'Вредоносные программные средства / Компьютерные вирусы': 'virus.jpg',
    'Высокопроизводительные вычисления': 'vichis.jpg',
    'Вычислительные сети / Администрирование локальных вычислительных сетей': 'admin_seti.jpg',
    'Вычислительные системы': 'vich_syst.jpg',
    'Геометрия': 'anal_geom.jpg',
    'Графическая визуализация и машинная графика': 'graf_vis.jpg',
    'Деловая коммуникация': 'del_com.jpg',
    'Дискретная математика': 'disc_math.jpg',
    'Дискретная математика и математическая логика': 'disc_math.jpg',
    'Дифференциальная геометрия': 'dif_geom.jpg',
    'Дифференциальные уравнения': 'dif_ur.jpg',
    'Документоведение': 'docs.jpg',
    'Дополнительные главы дискретной математики': 'disc_math.jpg',
    'Дополнительные главы математического анализа': 'math_anal.jpg',
    'Защита в операционных системах': 'def_seti.jpg',
    'Защита в операционных системах / Администрирование безопасности операционных систем': 'def_seti.jpg',
    'Защита информации': 'def_seti.jpg',
    'Защита информации / Случайные процессы': 'def_seti.jpg',
    'Защита информации от утечки по техническим каналам': 'def_seti.jpg',
    'Защита программ и данных': 'def_seti.jpg',
    'Защита систем управления базами данных': 'def_seti.jpg',
    'Иностранный язык': 'eng.jpg',
    'Интерфейсы периферийных устройств / Программная инженерия': 'algoritm_prog.jpg',
    'Информатика': 'infor.jpg',
    'Информационная безопасность': 'def_seti.jpg',
    'Информационная безопасность и защита информации': 'def_seti.jpg',
    'Информационные системы и технологии': 'admin_seti.jpg',
    'Информационные технологии': 'infor.jpg',
    'Искусственный интеллект': 'isk_int.jpg',
    'Искусственный интеллект и логическое программирование': 'isk_int.jpg',
    'Исследование операций и методы оптимизации': 'eng_it.jpg',
    'История': 'history.jpg',
    'История (история России, всеобщая история)': 'history.jpg',
    'История России': 'history.jpg',
    'История и методология математики': 'history.jpg',
    'История криптографии': 'history.jpg',
    'История математики в контексте истории культуры': 'history.jpg',
    'Квантовая кибернетика': 'isk_int.jpg',
    'Квантовые вычисления': 'isk_int.jpg',
    'Квантовые коммуникации': 'kvant_comm.jpg',
    'Кибернетика': 'isk_int.jpg',
    'Кибернетика / Метрология, стандартизация и сертификация': 'isk_int.jpg',
    'Командная проектная работа': 'com_proj_job.png',
    'Коммутация и маршрутизация': 'admin_seti.jpg',
    'Компиляторы и методы трансляции': 'compilar.jpg',
    'Комплексный анализ': 'comp_anal.jpg',
    'Комплексный анализ-2': 'comp_anal.jpg',
    'Компьютерная геометрия и геометрическое моделирование': 'graf_vis.jpg',
    'Компьютерная графика': 'graf_vis.jpg',
    'Компьютерная экспертиза': 'comp_eks.jpg',
    'Компьютерные сети': 'admin_seti.jpg',
    'Компьютерный практикум': 'infor.jpg',
    'Корпоративные информационные системы / Цифровая обработка сигналов': 'prog.jpg',
    'Криптографические методы защиты информации': 'def_seti.jpg',
    'Криптографические протоколы': 'def_seti.jpg',
    'Лямбда-исчисление': 'lyabda.jpg',
    'Математическая логика': 'math_log.jpg',
    'Математическая логика и теория алгоритмов': 'math_log.jpg',
    'Математическая статистика': 'analiz.jpg',
    'Математические основы экономики': 'analiz.jpg',
    'Математический анализ': 'math_anal.jpg',
    'Математическое моделирование': 'math_model.jpg',
    'Математическое моделирование в естествознании': 'math_model.jpg',
    'Математическое моделирование в естествознании / Архитектура электронно-вычислительных машин и ассемблеры': 'math_model.jpg',
    'Математическое моделирование в экономике': 'math_model.jpg',
    'Математическое моделирование в экономике / Графическая визуализация и машинная графика': 'math_model.jpg',
    'Математическое моделирование в экономике / Теория кодирования': 'math_model.jpg',
    'Машинное обучение': 'isk_int.jpg',
    'Машинное обучение / Дифференциальные уравнения-2': 'isc_int.jpg',
    'Междисциплинарный семинар': 'books.jpg',
    'Межкультурная и деловая коммуникация': 'del_com.jpg',
    'Менеджмент': 'infor.jpg',
    'Методология научного познания': 'metod_scientist.png',
    'Методы верификации': 'verif.jpg',
    'Методы вычислений': 'metod_scientist.png',
    'Методы и средства криптографической защиты информации': 'def_seti.jpg',
    'Методы и стандарты оценки защищённости компьютерных систем': 'def_seti.jpg',
    'Методы оптимизации': 'metod_scientist.png',
    'Метрология, стандартизация и сертификация': 'metrology.jpg',
    'Механика, основы механики сплошных сред': 'mech.jpg',
    'Модальные и дескриптивные логики': 'math_log.jpg',
    'Модели безопасности компьютерных систем': 'def_seti.jpg',
    'Моделирование социальных систем': 'soc_system.png',
    'Научно-исследовательский семинар / Научно-исследовательский семинар': 'metod_scientist.png',
    'Научно-исследовательский семинар / Научно-практический семинар': 'metod_scientist.png',
    'Научно-исследовательский семинар по прикладной математике / Научно-исследовательский семинар': 'metod_scientist.png',
    'Начертательная геометрия и инженерная графика': 'graf_vis.jpg',
    'Облачные вычисления': 'cloud_vich.jpg',
    'Обработка Big Data': 'analiz.jpg',
    'Объектно-ориентированный дизайн': 'dis_oop.jpg',
    'Операционные системы': 'oper_sys.jpg',
    'Организационное и правовое обеспечение информационной безопасности': 'def_seti.jpg',
    'Основные направления Data Science': 'analiz.jpg',
    'Основы информационного права': 'pravo.png',
    'Основы информационной безопасности': 'def_seti.jpg',
    'Основы компьютерных наук': 'prog.jpg',
    'Основы построения защищённых баз данных': 'def_seti.jpg',
    'Основы построения защищённых компьютерных сетей': 'def_seti.jpg',
    'Основы предпринимательства': 'infor.jpg',
    'Основы программирования': 'prog.jpg',
    'Основы российской государственности': 'rus_gos.jpg',
    'Основы теории управления': 'teor_upr.jpg',
    'Основы тестирования программного обеспечения': 'prog.jpg',
    'Основы управления информационной безопасностью': 'def_seti.jpg',
    'Основы управленческой деятельности / Основы менеджмента': 'meneg.jpg',
    'Основы управленческой деятельности / Основы теории управления': 'teor_upr.jpg',
    'Основы цифровых расследований': 'rasled.png',
    'Пакеты прикладных программ': 'metod_scientist.png',
    'Параллельные алгоритмы': 'parralel.jpg',
    'Правоведение': 'legal_security.jpg',
    'Правовые основы профессиональной деятельности': 'legal_security.jpg',
    'Практикум управления проектами': 'infor.jpg',
    'Преддипломная практика': 'books.jpg',
    'Прикладная физическая культура и спорт': 'fiz_ra.jpg',
    'Программирование для баз данных': 'prog.jpg',
    'Программирование мобильных устройств': 'prog_mobile.jpg',
    'Программирование на C++': 'c++.jpg',
    'Программирование на языке высокого уровня': 'web_prog.png',
    'Программирование серверных приложений': 'prog_serv.jpg',
    'Программирование сетевых приложений': 'admin_seti.jpg',
    'Программная инженерия': 'eng_it.jpg',
    'Программно-аппаратные средства защиты информации': 'def_seti.jpg',
    'Проектирование интеллектуальных систем': 'isk_int.jpg',
    'Проектирование информационных систем': 'prog.jpg',
    'Проектный практикум': 'com_proj_job.png',
    'Производственная практика: научно-исследовательская работа': 'metod_scientist.png',
    'Производственная практика: преддипломная практика': 'infor.jpg',
    'Производственная практика: технологическая (проектно-технологическая) практика': 'prac_tech.jpg',
    'Производственная практика: эксплуатационная практика': 'prog.jpg',
    'Производственная практика: эксплуатационно-технологическая практика': 'prak_proj_tech.jpg',
    'Психология общения': 'psyhology.jpg',
    'Разработка САПР': 'web_prog.png',
    'Разработка бизнес-приложений': 'prog_mobile.jpg',
    'Разработка бизнес-приложений (1С)': 'prog.jpg',
    'Распознавание образов': 'rasled.png',
    'Русский язык и культура речи': 'rus_lang.jpg',
    'Русский язык и культура речи / Практическая риторика': 'rus_lang.jpg',
    'Сети и системы передачи информации': 'admin_seti.jpg',
    'Сети и системы телекоммуникаций': 'admin_seti.jpg',
    'Сети и телекоммуникации': 'admin_seti.jpg',
    'Системное и прикладное программное обеспечение': 'algoritm_prog.jpg',
    'Системное и прикладное программное обеспечение-2': 'algoritm_prog.jpg',
    'Системы управления базами данных': 'DB.jpg',
    'Случайные процессы': 'rand.jpg',
    'Современные методы оптимизации': 'metod_optim.jpg',
    'Современные педагогические теории, системы и технологии': 'books.jpg',
    'Современные численные методы и пакеты прикладных программ': 'chis_metod.jpg',
    'Социальная кибернетика': 'soc_system.png',
    'Социальная кибернетика / Моделирование социальных систем': 'soc_system.png',
    'Социология': 'soc_system.png',
    'Социология / Социальная кибернетика': 'soc_system.png',
    'Социология / Социальные проблемы современного общества': 'soc_system.png',
    'Специализация': 'prak_proj_tech.jpg',
    'Специализация по прикладной математике': 'alg.jpg',
    'Специализация по прикладной математике / Специализация': 'alg.jpg',
    'Специализация по программированию / Специализация': 'prog.jpg',
    'Специализация по фундаментальной математике / Специализация по прикладной математике': 'math_anal.jpg',
    'Структуры и алгоритмы компьютерной обработки данных': 'analiz.jpg',
    'Суперкомпьютерные технологии / Пакеты прикладных программ': 'eng_it.jpg',
    'Теоретико-числовые методы в криптографии': 'chis_metod.jpg',
    'Теоретическая механика': 'mech.jpg',
    'Теория автоматов': 'teor_aut.jpg',
    'Теория автоматов и формальных языков / Дифференциальная геометрия': 'teor_aut.jpg',
    'Теория алгоритмов и сложности вычислений': 'teor_alg.jpg',
    'Теория вероятностей': 'teor_ver.jpg',
    'Теория вероятностей и математическая статистика': 'teor_ver.jpg',
    'Теория вычислимости': 'teor_vic.jpg',
    'Теория графов и комбинаторные алгоритмы': 'teor_graf.png',
    'Теория игр': 'teor_ver.jpg',
    'Теория игр и исследование операций': 'teor_ver.jpg',
    'Теория информации': 'infor.jpg',
    'Теория категорий и топосы': 'teor_kateg.jpg',
    'Теория систем и системный анализ': 'analiz.jpg',
    'Теория функций комплексного переменного': 'teor_func_comp.jpg',
    'Техническая защита информации': 'def_seti.jpg',
    'Технологии и методы программирования': 'algoritm_prog.jpg',
    'Технологии разработки программного обеспечения': 'prog_serv.jpg',
    'Топология': 'topology.jpg',
    'Удалённый доступ и компьютерные сети': 'admin_seti.jpg',
    'Управление проектированием информационных систем': 'infor.jpg',
    'Уравнения математической физики': 'urav_math_phyz.jpg',
    'Учебная практика: научно-исследовательская работа (получение первичных навыков научно-исследовательской работы)': 'books.jpg',
    'Учебная практика: ознакомительная практика': 'eng_it.jpg',
    'Учебная практика: практика по получению первичных профессиональных умений и навыков': 'prak_proj_tech.jpg',
    'Учебная практика: практика по получению первичных профессиональных умений и навыков, в том числе первичных умений и навыков научно-исследовательской деятельности': 'prak_proj_tech.jpg',
    'Учебная практика: проектная практика': 'infor.jpg',
    'Учебная практика: технологическая (проектно-технологическая) практика': 'prog.jpg',
    'Физика': 'phyzik.jpg',
    'Физическая культура и спорт': 'fiz_ra.jpg',
    'Физическая культура и спорт (спортивное совершенствование)': 'fiz_ra.jpg',
    'Философия': 'filosof.jpg',
    'Функциональное программирование / Программная инженерия': 'prog.jpg',
    'Функциональный анализ': 'funk_anal.jpg',
    'Функциональный анализ-2': 'funk_anal.jpg',
    'Цифровая обработка сигналов / Корпоративные информационные системы': 'prog_serv.jpg',
    'Численные методы': 'funk_anal.jpg',
    'ЭВМ и периферийные устройства': 'algoritm_prog.jpg',
    'Экология': 'ecology.jpg',
    'Экономика': 'analiz.jpg',
    'Экономика фирмы': 'analiz.jpg',
    'Экономическая безопасность': 'eco_def.jpg',
    'Электроника и схемотехника': 'electro_shema.png',
    'Электротехника': 'elertro_tech.jpg',
    'Языки и методы программирования': 'prog_lang.jpg',
    'Языки программирования': 'prog_lang.jpg',
  };

  static Map<String, String> listOfUrl = {
    'Web-программирование': '1AWQxeVXMs71CXHjkySWSaWTFN5ULK5QN?usp=sharing',
    'SMM-продвижение': '1ENBXsn5nLEGO0_8P4Fz1_-L34qV7v7gi?usp=sharing',
    'Администрирование сетевых операционных систем': '1Ex3lrwo6SJbbBLNXKEIvlea-d8YV4j_c?usp=sharing',
    'Алгебра': '1jNpP-bbOXomgs4QGm2ANLcDhhw84KuC0?usp=sharing',
    'Алгебра и геометрия': '1ukrGLf1g2yEOBGz4ouiVv-W3H0LMlwUk?usp=sharing',
    'Алгебра и теория чисел': '1fI8JMcI7JUFV3ZWc2GY-JeuIn4cViUSB?usp=sharing',
    'Алгоритмизация и программирование': '1eCVzXOnv666Vm5ereSVw17nhPgIuBLYJ?usp=sharing',
    'Алгоритмы анализа данных и машинное обучение / Веб-программирование': '177HCBtG8jyxErazVGbfPmvH_-8_bNg1z?usp=sharing',
    'Алгоритмы анализа изображений': '1jF0aB0cn84emBibwXzKJIwnkBxD9vT0o?usp=sharing',
    'Алгоритмы кодировки и сжатия': '1UXL5vPW8p7qpuUvWmeGFsPH0gPZnmPwm?usp=sharing',
    'Алгоритмы спектрального анализа данных / Защита сетевого периметра': '1qVrrVA3VIeBjJJQ6KHrGMnDnYmzBBBOE?usp=sharing',
    'Анализ статистических данных': '1q0KLPFJJGmEEXBtSFdhifR2eXLeZHWTg?usp=sharing',
    'Анализ уязвимостей компьютерных сетей': '1UjE2WR2DZ5L4frHqy06tXTbAfJTW8xyX?usp=sharing',
    'Анализ уязвимостей программного обеспечения': '1ubanqSIP9ALaqnm3BTvV3IkG6VfqBK8n?usp=sharing',
    'Анализ уязвимостей программного обеспечения / Безопасность программного кода': '1tzp-37GdJE2QxMwafa1Xzjo9ROhx7115?usp=sharing',
    'Аналитическая геометрия': '1VAUV4tf4RylUP5OVNvnV80ryQDnQ_XZp?usp=sharing',
    'Аппаратные средства вычислительной техники': '1ansxumX56Uqxix8Og5jIiZuazxpmnlZF?usp=sharing',
    'Ассемблер': '1XzROMKthQRJddrd8FxQinR_CIosKRzgH?usp=sharing',
    'Базы данных': '1EprZ4Kotpo8Jzk6MTYvTbxdp48YyqDa2?usp=sharing',
    'Безопасность жизнедеятельности': '1DM0J3p66WbhIQ_qODfruDDemJgVj-FxD?usp=sharing',
    'Бизнес-английский язык в IT': '1H1nAU8-MPX_8LpsvV8MXEVUPONqFsB2d?usp=sharing',
    'Биоинформатика': '1X0HcuLdJ1qvZvUc7-3LSYDbKlwE3MN66?usp=sharing',
    'Вариационное исчисление и оптимальное управление': '1w00xAG0EzMPsQutB8nxoOnBvH5JHc3e6?usp=sharing',
    'Введение в прикладную математику': '12IU698EbkjHKnlYrJbCteBK27stLxU9T?usp=sharing',
    'Введение в программирование': '1Dz818otaozkeXlav6eMUTWKHmNXUXdsW?usp=sharing',
    'Вредоносные программные средства': '18ygXBmo7vG3UATzRbvCR0XG_3wpc1jOp?usp=sharing',
    'Вредоносные программные средства / Компьютерные вирусы': '1fHFV-8Adh-IkqYiUkAsyyiMbukq9Nual?usp=sharing',
    'Высокопроизводительные вычисления': '1PbNwHYHE6MqiAYWLNKj6CIUW8yTStYoU?usp=sharing',
    'Вычислительные сети / Администрирование локальных вычислительных сетей': '14Bkbci0MvMBE6eZQ45CYy0fux5xcBe9m?usp=sharing',
    'Вычислительные системы': '1qe4_ONFeu8dCTQ6phjal3mFttflmqQhX?usp=sharing',
    'Геометрия': '1ssHpEKJL30DWsBZ8RhZz671-4fI3JsFr?usp=sharing',
    'Графическая визуализация и машинная графика': '1Kx5BMAZLWtIWuCO-nfXyVx5sasLkHExX?usp=sharing',
    'Деловая коммуникация': '1kzJjGjfAm1LY_jxoiwosXjO8knszlf-K?usp=sharing',
    'Дискретная математика': '1QiUfnj1LKXTA9kwefOWQ4kMb0k0wq1uM?usp=sharing',
    'Дискретная математика и математическая логика': '1cgV01E4OwiSS0NyaWhJ92d8Q02i-InqX?usp=sharing',
    'Дифференциальная геометрия': '1MiCab5GSGgETaWikiy6WZLqWlUsr7v5T?usp=sharing',
    'Дифференциальные уравнения': '1YTFF7gNuCoHqslBTSgzaoDcncxHd0bxO?usp=sharing',
    'Документоведение': '1Rq8K_nOLM3ty8FMynaS2dg84qYXKaT91?usp=sharing',
    'Дополнительные главы дискретной математики': '1E_hF7AOg3mw15nbSQVDUkpyX0Hc2fHdE?usp=sharing',
    'Дополнительные главы математического анализа': '1q8y-prvusei1-mZOHVkIE0FdqjiE88JE?usp=sharing',
    'Защита в операционных системах': '1IJWsXPERNCNi7NUu26CiAKsfdxAsq0Tj?usp=sharing',
    'Защита в операционных системах / Администрирование безопасности операционных систем': '16FlYwhvg8lBmoO4JBuO-bHZfe5q-d0N2?usp=sharing',
    'Защита информации': '1GiRBjK7txsOZw11omJno0vO3DvdluKv7?usp=sharing',
    'Защита информации / Случайные процессы': '1tVP69G4GpZtqwOEOUkU1aGkjzQomgDG7?usp=sharing',
    'Защита информации от утечки по техническим каналам': '15LVvygbrOrM-yfKWeGJlatjItiLRjB3S?usp=sharing',
    'Защита программ и данных': '1g6xaxdtWr_iQyy5ibEO1ygEGfWvR2d3J?usp=sharing',
    'Защита систем управления базами данных': '1erVIqMzCjoZZA5JxuHJlIgkMl6JEjYbE?usp=sharing',
    'Иностранный язык': '144YcoL1NCWJo07qAJToTxGmIRWJSJfN2?usp=sharing',
    'Интерфейсы периферийных устройств / Программная инженерия': '1g5MhFba199mTCodwSTTPtcyPXlm1rXgr?usp=sharing',
    'Информатика': '1xp1UU9lh-y8jXah6MhQR1pUka77_Myjm?usp=sharing',
    'Информационная безопасность': '1F4IO1hjl9bw5933JIIwk3hNS12J18ymv?usp=sharing',
    'Информационная безопасность и защита информации': '1wVK-j00vu989ZZjb1jIT_6nOjTOdc2xs?usp=sharing',
    'Информационные системы и технологии': '1FmxayBq_Q4UWh6zRTra12urIXWAryaAT?usp=sharing',
    'Информационные технологии': '1jsz1-4FaM5julmF1S_nBKrwnuQptP0dw?usp=sharing',
    'Искусственный интеллект': '1eqUot3jTvYyzHoxbz_f9ltTMExHlUOmV?usp=sharing',
    'Искусственный интеллект и логическое программирование': '14S8UuUfHV530uvzJAoPF1K63qh9utQyO?usp=sharing',
    'Исследование операций и методы оптимизации': '1qBYd-b2V14-GMnTosVilzqGuSqIeubeD?usp=sharing',
    'История': '16oN2hye2czvmBz-5qYWbmyfFypJXsWk2?usp=sharing',
    'История (история России, всеобщая история)': '1etQhEaIK6kojECpOb16wOpQl3-MMVU7M?usp=sharing',
    'История России': '1VzE1uXeHeCKPPGFB-IoeTbNEZhPng6MU?usp=sharing',
    'История и методология математики': '1t4rd8c978eo3Q4rDpEpGHPYDIGrR69o7?usp=sharing',
    'История криптографии': '1Cc0N7GyD3Mxxr8-ni3G3Lcd8Du43Afxv?usp=sharing',
    'История математики в контексте истории культуры': '1Xo1E0sAaPzWJsb-P65QKhCIKD-T_kCby?usp=sharing',
    'Квантовая кибернетика': '1GuFU_O5WPPWGrQ683iHkAirBRG5e__f-?usp=sharing',
    'Квантовые вычисления': '18x4km71GQAIjbkYJorXkwFINaXmqPLHs?usp=sharing',
    'Квантовые коммуникации': '1r8PrLsbPkh17Xvu69mml3jl9vz89_WrK?usp=sharing',
    'Кибернетика': '17ZSoUtLlmoeyUgXQPh5ZoecOPydnioLG?usp=sharing',
    'Кибернетика / Метрология, стандартизация и сертификация': '1k85ajz_0Q4yFl5uury4gbI7bj7emfpJO?usp=sharing',
    'Командная проектная работа': '1FOo72xVJBhkq1xZ-hS3bR9VXRbsx9GZo?usp=sharing',
    'Коммутация и маршрутизация': '12QNRa8b5EY2T394lM2ER_-6Fkq24IDSh?usp=sharing',
    'Компиляторы и методы трансляции': '1V17ecbmAe0L8ySUpgWWHdAuFNTeelbFg?usp=sharing',
    'Комплексный анализ': '1D-6b5SiiOXtnVRkRn1AULIxfEdR7p8Jo?usp=sharing',
    'Комплексный анализ-2': '1jvtcXVqgS6paYjOt4-9RRX9oVAYvECoX?usp=sharing',
    'Компьютерная геометрия и геометрическое моделирование': '1_7x07hRVAsRfaIV1jXJcEEeoqR_sxxuV?usp=sharing',
    'Компьютерная графика': '1kK-rVw4wJIy951YbldiPGIhQIR6HCzeS?usp=sharing',
    'Компьютерная экспертиза': '17fHkvRRZGHsVEnmb1lVi7toHa5HosSBl?usp=sharing',
    'Компьютерные сети': '1ddcWgCUYSsR2LUa1DSP5xtqc_UC_mIVa?usp=sharing',
    'Компьютерный практикум': '1sPLFlbwUkHV08rPw4_NI-lv6wbBhWm0O?usp=sharing',
    'Корпоративные информационные системы / Цифровая обработка сигналов': '1gCxUauvfWrUlOQTbO0H_Oj-B1Ic6YqkF?usp=sharing',
    'Криптографические методы защиты информации': '1vA9ihZRNC9aO284W_svYc_9zBTKCOXqb?usp=sharing',
    'Криптографические протоколы': '1Av4QHvkCreGTLyZdu8zpIxLP1p3OfkdX?usp=sharing',
    'Лямбда-исчисление': '1K7IABjcxH5CHdYAyLwxsZlcIA1cvNUDJ?usp=sharing',
    'Математическая логика': '1BFqVHDuMy9Pw5Yyr2wJzHcOd_vKDttH4?usp=sharing',
    'Математическая логика и теория алгоритмов': '1hfC-LyD4_Ks535aaOKO8ZlfosbIElTd4?usp=sharing',
    'Математическая статистика': '1ZdgHXBDhygja15jBab0VLY45iP116Ycz?usp=sharing',
    'Математические основы экономики': '1PSI0vsT_V4RgDuBHOhaLcnfvcLVtX3G6?usp=sharing',
    'Математический анализ': '19nGdkLDqrITneFKNOzfMR50CHsuyApra?usp=sharing',
    'Математическое моделирование': '1Dhf3do8tPYwG9T7ySPZxNDgeRSBW2zng?usp=sharing',
    'Математическое моделирование в естествознании': '1x36gFD_eQ8iHXg-zuBD_Lcon5l8IPN5Q?usp=sharing',
    'Математическое моделирование в естествознании / Архитектура электронно-вычислительных машин и ассемблеры': '1gzBDIW7MusOjFvTRGUs4Z6Ey6tHnB6WM?usp=sharing',
    'Математическое моделирование в экономике': '1rhIEGRYPyUuu_cyMBsCUqYQC1iSN_sQE?usp=sharing',
    'Математическое моделирование в экономике / Графическая визуализация и машинная графика': '1M8xEFChlrZ-O4rnfnSl7nPrvt19wn_cx?usp=sharing',
    'Математическое моделирование в экономике / Теория кодирования': '1h6FIIcfQNzq97nWfirq_yoLCmU-qWRbq?usp=sharing',
    'Машинное обучение': '16nxTdxViKdpjgFTwGU3n3HXu_F2u8XAr?usp=sharing',
    'Машинное обучение / Дифференциальные уравнения-2': '1Upc8wTlUCUIqSrW2qAFwUzbl9Ibi3k-8?usp=sharing',
    'Междисциплинарный семинар': '1gRiBVTyqx2M9n46g44VythmMq5j-mDze?usp=sharing',
    'Межкультурная и деловая коммуникация': '1t68TOvCnDsgwkmK-D_Ch1Z-J5htGSw1O?usp=sharing',
    'Менеджмент': '1Pan5-YAaHRxEXMdGJ7ipVA6OSyo3rOhq?usp=sharing',
    'Методология научного познания': '1iWOGroo_qc92e1InlCe8xKADZTy67YJm?usp=sharing',
    'Методы верификации': '1WFykIY0f-kEy7sAUbQE_3Db_kG9doppl?usp=sharing',
    'Методы вычислений': '1s7bAO1lS_Q_cARuamsNHSPqUYNsAT1oy?usp=sharing',
    'Методы и средства криптографической защиты информации': '17f7cbJfoFNWbe9hvvkrEcfb39Oii4jWy?usp=sharing',
    'Методы и стандарты оценки защищённости компьютерных систем': '1JKEEGtmlx-V8tf5A7Mkjk26FzwHXiFok?usp=sharing',
    'Методы оптимизации': '1XyBaLZqdd06BqQ_4H5Qa02kCgGZyJjv_?usp=sharing',
    'Метрология, стандартизация и сертификация': '1SxtMopCabUGrlzkB3e6PPTRivttcxm6t?usp=sharing',
    'Механика, основы механики сплошных сред': '1krCsQZnikfZWuQeH2ur7-T04dAIQzif4?usp=sharing',
    'Модальные и дескриптивные логики': '1HXtgNAYitpqYG-JlqvWEV8Jk9dNYunvE?usp=sharing',
    'Модели безопасности компьютерных систем': '1tdACLzmK-Om5MgciHnCliKAmO1m2LXWA?usp=sharing',
    'Моделирование социальных систем': '1rbXCFvW4KTMJfVNv0ovlJkcofBa87UZx?usp=sharing',
    'Научно-исследовательский семинар / Научно-исследовательский семинар': '1YJErFryQ8DpWxBlI4nq6sy5TWfvnFDmT?usp=sharing',
    'Научно-исследовательский семинар / Научно-практический семинар': '1y-JF9kup5kXcCTB_qVCXP_DLcqLYZFuG?usp=sharing',
    'Научно-исследовательский семинар по прикладной математике / Научно-исследовательский семинар': '1hgdUHENkuFgrXSZ10fMw6G0Q-r1f5rM2?usp=sharing',
    'Начертательная геометрия и инженерная графика': '1UwgBrRy5BiOsNRTxHfyo8krbmXnbQ2kq?usp=sharing',
    'Облачные вычисления': '1xO2t3prUUz8PUzK3Mt52APfdPZoQnNqP?usp=sharing',
    'Обработка Big Data': '1jjPDYU7imLnpyihlcHMtiWHhfmjxsYzC?usp=sharing',
    'Объектно-ориентированный дизайн': '18S9brgQRvdSDKSSxNjRgr4vlkQQWzlKt?usp=sharing',
    'Операционные системы': '1YV2nyDNpCyfDNpexlZBSKQUGGilgh2JW?usp=sharing',
    'Организационное и правовое обеспечение информационной безопасности': '13URX2WShQW-6R8P9YmEYgNm0Bt0ZVev8?usp=sharing',
    'Основные направления Data Science': '101IbiE4WicuKgAXiwePWppwU2JxfBEFy?usp=sharing',
    'Основы информационного права': '1A47kBcjpCPe0OeuMPSpa5ihFS10QBGWL?usp=sharing',
    'Основы информационной безопасности': '1-0yDh9A0mjPJ0LSiFFBn2OMUCzweKIRp?usp=sharing',
    'Основы компьютерных наук': '1oWBv6G044RRdAEzds7fCVSqx99UfxOo9?usp=sharing',
    'Основы построения защищённых баз данных': '13dJ8gz2T9M1EDrhA65dwcnnuAyv4uGbE?usp=sharing',
    'Основы построения защищённых компьютерных сетей': '1vqYk9IgrfVL8qmFQnD8w4m9SIOGrBNWp?usp=sharing',
    'Основы предпринимательства': '1O7_dPm9L6_Y6ejcw-Ad4myNe0aNhi6F7?usp=sharing',
    'Основы программирования': '1qsDVJSmN-Kwb8aKkv-vvMNz6B59Fz0pQ?usp=sharing',
    'Основы российской государственности': '1CzBHI8RTeN_huOSF2T0cP5ek6kbp7CPX?usp=sharing',
    'Основы теории управления': '1bEM5KE5uiXhCZ8GFqGvnPY6DBPZwntlX?usp=sharing',
    'Основы тестирования программного обеспечения': '1AGU8VxGXeUrtaDkBkCqv6W1W0dZvNjc5?usp=sharing',
    'Основы управления информационной безопасностью': '119aF7Yi-yL8lo7QVUeAxXnHp-C9JdK3N?usp=sharing',
    'Основы управленческой деятельности / Основы менеджмента': '1dCMfaZu0YT_DIri7TBshNmrhacr3BZTP?usp=sharing',
    'Основы управленческой деятельности / Основы теории управления': '1jdepppjNPoF-COGfBvCLIyQH_5Gu3r-V?usp=sharing',
    'Основы цифровых расследований': '19l8zFfg8pZViRdAY35kBjwDVTJ8uBAvu?usp=sharing',
    'Пакеты прикладных программ': '1z965aHUQIjDl2SW0QssaL-hZXj4CZIpP?usp=sharing',
    'Параллельные алгоритмы': '1aLjh-1xKseL3eYUe3kW6OzD_YC-QfuwY?usp=sharing',
    'Правоведение': '1joBx44oYZyafyleF6oQJw4sE0hkxeeZX?usp=sharing',
    'Правовые основы профессиональной деятельности': '1H5R913z1ngJXX-OM-Wax-jKdhRW24KXq?usp=sharing',
    'Практикум управления проектами': '1SNfohe6uRRHzy1B0CaE76wXZGL6ICMx-?usp=sharing',
    'Преддипломная практика': '1e7AWoq6j9e-dYzYftt-FUuAQJXKkN54a?usp=sharing',
    'Прикладная физическая культура и спорт': '1d-K7etEgcaTcaJ44Di7KlhyPaH7-3DOe?usp=sharing',
    'Программирование для баз данных': '1sAGtWxZWNTZ-vIiX5biLs95GYCVa_fqy?usp=sharing',
    'Программирование мобильных устройств': '1C4faJ0Q3_7uMN8Ie511qz5o5bp0jE54z?usp=sharing',
    'Программирование на C++': '1O609HnwJ_Yv5a3y4wATtMiPWfXheXIMP?usp=sharing',
    'Программирование на языке высокого уровня': '11NT10tcXphn_f8RFVNgVptSjxPMz1PZ6?usp=sharing',
    'Программирование серверных приложений': '154_ByyX4zOfdIlOwrTPkckjrKQ84RiQt?usp=sharing',
    'Программирование сетевых приложений': '1dyyQMHiKLV1hSCd_PmYN6xXME0c1kMBU?usp=sharing',
    'Программная инженерия': '1KN23qVTZO8j_cZnSrYtMXhzTlTkYc8rH?usp=sharing',
    'Программно-аппаратные средства защиты информации': '1TVINOttjdJogPJrN3HPeCsyJxb6DheJ6?usp=sharing',
    'Проектирование интеллектуальных систем': '1nSFnZ6T544vW3H_bquUa0BB-WzEkDhTw?usp=sharing',
    'Проектирование информационных систем': '1sReKoq7ND_mZRrUA7E76T9m9nSwTm4sR?usp=sharing',
    'Проектный практикум': '1WpegkiFLCppJE9sUS1zb4KhxuPYEvlGu?usp=sharing',
    'Производственная практика: научно-исследовательская работа': '1N8_nZchyfryREMpomuSqq6AUyn9oSQTB?usp=sharing',
    'Производственная практика: преддипломная практика': '1L80m23qxZnCeNVZOnD_pEdmL87glL-eO?usp=sharing',
    'Производственная практика: технологическая (проектно-технологическая) практика': '14ZjBEL8Qn5ry1C0NDkSD5lBBCgcpMG8l?usp=sharing',
    'Производственная практика: эксплуатационная практика': '1CaIkTiexZaXGNAM-QrEAVndK4X8FU8FN?usp=sharing',
    'Производственная практика: эксплуатационно-технологическая практика': '1BSIQd0Ec2VVemsT4vbou_sEevH60Pt_-?usp=sharing',
    'Психология общения': '1hJ9leX5pHTKVc9wI3ymh4ISPFPnMsMzE?usp=sharing',
    'Разработка САПР': '1S7dFnfHEC8R1nCRvtzmnFMXtCCKrtPwU?usp=sharing',
    'Разработка бизнес-приложений': '1WYcu7ROZ30pbvEjjDigf8jxbOvRQQTF4?usp=sharing',
    'Разработка бизнес-приложений (1С)': '1A6Br8UiM8zHzt7ugJf9Lwgcvw-qP0Bt0?usp=sharing',
    'Распознавание образов': '1BJwS_I2RbjWLvUtaFVHpnD9kPBQsLzz4?usp=sharing',
    'Русский язык и культура речи': '150e3TORQkl_R-hfohrdUZv4DCLBFQ9UY?usp=sharing',
    'Русский язык и культура речи / Практическая риторика': '1n8-l6SHmZOppmdAKtCVFEzrNpROLiFqO?usp=sharing',
    'Сети и системы передачи информации': '1yLE50pw-By1QEXm7v7fB21EVrtrM1d3B?usp=sharing',
    'Сети и системы телекоммуникаций': '1ck0wRSbofvf7Z7CljkAOlsASbgVjJT9S?usp=sharing',
    'Сети и телекоммуникации': '168ULmuK6oFp4TSmx_5MOtlCze_sqf_t4?usp=sharing',
    'Системное и прикладное программное обеспечение': '1IUmM0HLbcRXr97k8tlxt0EUWkPPXkQCo?usp=sharing',
    'Системное и прикладное программное обеспечение-2': '1eUZTmjmaxPnoOgMEWusrlX9TflIFlrBQ?usp=sharing',
    'Системы управления базами данных': '1Jm-L7H7aC6QyE2QBQGJ4Jp_J1F0_btkq?usp=sharing',
    'Случайные процессы': '1UTyF3LcFvN2tt9ptUkCd4CIrKHTKyikV?usp=sharing',
    'Современные методы оптимизации': '1YlehGOkkdQPFbHN7wJCQUpl6EBGireLk?usp=sharing',
    'Современные педагогические теории, системы и технологии': '1nSgmJpy_O19Sp6Ar-aT4Mk8WhXFpcnYb?usp=sharing',
    'Современные численные методы и пакеты прикладных программ': '1808Xb94VKEMgq-RE2eLSRjQL8whf-ELj?usp=sharing',
    'Социальная кибернетика': '13dBJVhyIGzfrItIQWx3JsFjEjSONXErb?usp=sharing',
    'Социальная кибернетика / Моделирование социальных систем': '1OdIc83-cz7b-G6XsLtyqximwQQECjLq5?usp=sharing',
    'Социология': '1IuYT6pFB9KT3iR-wkUXnMuyIHbxaNAI6?usp=sharing',
    'Социология / Социальная кибернетика': '1AE9zoVxrTQnWj3OgetQjHsnUzyK5LIHM?usp=sharing',
    'Социология / Социальные проблемы современного общества': '1AK8ac4e7qOMnpQDX9dJYgKPPrE8FHER3?usp=sharing',
    'Специализация': '10ekP4TewOXUITx3UTOjjnxW-xU5dsB-s?usp=sharing',
    'Специализация по прикладной математике': '1GHctrrUvxA26m3dv2raWGByUf6n8UScb?usp=sharing',
    'Специализация по прикладной математике / Специализация': '1MRFSnJJOCpS5U_R8TvJgNHbxZAN87jwz?usp=sharing',
    'Специализация по программированию / Специализация': '1-ECRjMmvCB4jXpHaamfWTmVfjQAYLCQC?usp=sharing',
    'Специализация по фундаментальной математике / Специализация по прикладной математике': '1mrb6QGvSBc29CYKSU5CTtLD-uTu25Dm_?usp=sharing',
    'Структуры и алгоритмы компьютерной обработки данных': '1ujBDAZ-RN0N6O_A9n4JjN-ppONr7d5g0?usp=sharing',
    'Суперкомпьютерные технологии / Пакеты прикладных программ': '1Z4TW94fQmdaLVCR_BiexvAjHuSg4RogX?usp=sharing',
    'Теоретико-числовые методы в криптографии': '18BO3dqA3Bl2Hz5PlWShroYt3deBR9TDP?usp=sharing',
    'Теоретическая механика': '1yPy7dZr1-5ZGP0kBumpFjDrwkJIR2N6h?usp=sharing',
    'Теория автоматов': '1Zj_iwTojCbVu-rxjibpFzbnnW4k7OEqM?usp=sharing',
    'Теория автоматов и формальных языков / Дифференциальная геометрия': '1Y0Wfz9nfACBwufj0xQIZWcPgbtqmYCqY?usp=sharing',
    'Теория алгоритмов и сложности вычислений': '1TwKvA6C2UeAJD8ZpGEdym149V3MFLBIW?usp=sharing',
    'Теория вероятностей': '1ICgHQGYHTCu0rsv7ma49VLE9mRdlEKRB?usp=sharing',
    'Теория вероятностей и математическая статистика': '1AIP4GgsXlspH_QKPsltXKDHWRkTxL8vL?usp=sharing',
    'Теория вычислимости': '14-EPzC-bxO-COClNDshvnaag8ZFtmT8B?usp=sharing',
    'Теория графов и комбинаторные алгоритмы': '1HvSDF86UUOaldBSEAsj9VFazL2k1Smr_?usp=sharing',
    'Теория игр': '1AC5XM_HKNZf-R45xR1nfNJgxt9PxzFZN?usp=sharing',
    'Теория игр и исследование операций': '1LGKtI3HeUC0VOqy3UKnh5v4pb7S81uuq?usp=sharing',
    'Теория информации': '1pPHc546gzPuRA3RELWWwYJqMBP-k0bsY?usp=sharing',
    'Теория категорий и топосы': '1Mvt8sq4wHJ3p-e1DpVdtITkDxyGHWFZ9?usp=sharing',
    'Теория систем и системный анализ': '1FSsMYITHagUDeu-Kv-0gHIskFP2tyLt3?usp=sharing',
    'Теория функций комплексного переменного': '1dCZSjVTqdXAiaUbf0VqVtrZ7usllYWLZ?usp=sharing',
    'Техническая защита информации': '1-FkpW2LEe7dYERrFif3CNCzlxr9z6dH4?usp=sharing',
    'Технологии и методы программирования': '1SJ0cLZIWyK1S34qNkod5Iyyjwo4dv4be?usp=sharing',
    'Технологии разработки программного обеспечения': '1wm75EWOdDQJzRqyzBVu0rRXSfaHBAy51?usp=sharing',
    'Топология': '1yhk9xBCHP2F5zlcYZGRUmeAXAOYm4oQM?usp=sharing',
    'Удалённый доступ и компьютерные сети': '17ON93Y_ULUS2lVgVULL3jBAoAdMyJjRf?usp=sharing',
    'Управление проектированием информационных систем': '16OC4E9opNqROG27iF3_PJzhQb90K2ztZ?usp=sharing',
    'Уравнения математической физики': '1M_CzdyEC4eH1dhIB211lQr2J6A3XF4T7?usp=sharing',
    'Учебная практика: научно-исследовательская работа (получение первичных навыков научно-исследовательской работы)': '1fB7BMxdflmoX94UyftJ3UpiwSXbBMd5j?usp=sharing',
    'Учебная практика: ознакомительная практика': '1MGU9YNbqQR1_VlA_Qa01O6h5DVzn186J?usp=sharing',
    'Учебная практика: практика по получению первичных профессиональных умений и навыков': '1KKPeliBALx6XPtBo4xe0H3H8PhkJxKAO?usp=sharing',
    'Учебная практика: практика по получению первичных профессиональных умений и навыков, в том числе первичных умений и навыков научно-исследовательской деятельности': '1ikUR2NxrbuuIwQ_zFxbwBRFneIL8jfW1?usp=sharing',
    'Учебная практика: проектная практика': '1XkmVZrQ0AOXa5V2BUGveUdI_eEhyPrLV?usp=sharing',
    'Учебная практика: технологическая (проектно-технологическая) практика': '1iwtMLNiGFY-mzhYxN2MZm3MPWuymxQbV?usp=sharing',
    'Физика': '19DWXQ3-6CsRNKj2nz3KaE7FZedXYG3AE?usp=sharing',
    'Физическая культура и спорт': '1gQMCQKU_8YjPivEwUtn0jHUEmmmAIcbh?usp=sharing',
    'Физическая культура и спорт (спортивное совершенствование)': '1lf3O8wdWxDCWb68OrslnTMGTf8B2ZQ7U?usp=sharing',
    'Философия': '1qfPgxpeLQ6G5mq1lVOG9sOEMWGelzI1c?usp=sharing',
    'Функциональное программирование / Программная инженерия': '1SAuL1nyJMwsjt5swf-isomuz6qiVUN5Q?usp=sharing',
    'Функциональный анализ': '1AwTk4tkyEjnSRS5zsHO_kyHLLwQRyuYG?usp=sharing',
    'Функциональный анализ-2': '1VhJXBHGo5y_P60XEuM2UJjHvYuCZZtZd?usp=sharing',
    'Цифровая обработка сигналов / Корпоративные информационные системы': '1H3JGapnUUs3ESCUL1HCcUovQGTgBJZST?usp=sharing',
    'Численные методы': '1YT0mmvnan29JMaMm5qJfqlCzRwt_BIwu?usp=sharing',
    'ЭВМ и периферийные устройства': '1jea4a4oWuxFTOsoZLXbNeELdeBfB5fzN?usp=sharing',
    'Экология': '1035KzsqMO_kXdJUUNo__I9MDiXh3q_SB?usp=sharing',
    'Экономика': '1VwzRjOdzEoR4IiAgVJ41d6WyvgBNFUo-?usp=sharing',
    'Экономика фирмы': '1Xl8pyKHRhD-j3lYosoJxoXCrSgqsLuUG?usp=sharing',
    'Экономическая безопасность': '12tcwRkQZOfNtEe7CWBLGCv8D9Io4df9Q?usp=sharing',
    'Электроника и схемотехника': '10u41imQhSdSPeGWt4vPl5Ow0hLpXFsMH?usp=sharing',
    'Электротехника': '1GNyrTX6-S0YBMFZid2PFia94wVnajd6w?usp=sharing',
    'Языки и методы программирования': '16pfkUpSpiIw_uLN0f8dwNYUHw3Qci6fd?usp=sharing',
    'Языки программирования': '1-HpOP0czmcAMTgE1wBXyqb1guY_Kw_Sc?usp=sharing',
  };

  static Map<String, String> listOfItemsAndTeachers = {
    'Web-программирование': '1AWQxeVXMs71CXHjkySWSaWTFN5ULK5QN?usp=sharing',
    'SMM-продвижение': '1ENBXsn5nLEGO0_8P4Fz1_-L34qV7v7gi?usp=sharing',
    'Администрирование сетевых операционных систем': '1Ex3lrwo6SJbbBLNXKEIvlea-d8YV4j_c?usp=sharing',
    'Алгебра': '1jNpP-bbOXomgs4QGm2ANLcDhhw84KuC0?usp=sharing',
    'Алгебра и геометрия': '1ukrGLf1g2yEOBGz4ouiVv-W3H0LMlwUk?usp=sharing',
    'Алгебра и теория чисел': '1fI8JMcI7JUFV3ZWc2GY-JeuIn4cViUSB?usp=sharing',
    'Алгоритмизация и программирование': '1eCVzXOnv666Vm5ereSVw17nhPgIuBLYJ?usp=sharing',
    'Алгоритмы анализа данных и машинное обучение / Веб-программирование': '177HCBtG8jyxErazVGbfPmvH_-8_bNg1z?usp=sharing',
    'Алгоритмы анализа изображений': '1jF0aB0cn84emBibwXzKJIwnkBxD9vT0o?usp=sharing',
    'Алгоритмы кодировки и сжатия': '1UXL5vPW8p7qpuUvWmeGFsPH0gPZnmPwm?usp=sharing',
    'Алгоритмы спектрального анализа данных / Защита сетевого периметра': '1qVrrVA3VIeBjJJQ6KHrGMnDnYmzBBBOE?usp=sharing',
    'Анализ статистических данных': '1q0KLPFJJGmEEXBtSFdhifR2eXLeZHWTg?usp=sharing',
    'Анализ уязвимостей компьютерных сетей': '1UjE2WR2DZ5L4frHqy06tXTbAfJTW8xyX?usp=sharing',
    'Анализ уязвимостей программного обеспечения': '1ubanqSIP9ALaqnm3BTvV3IkG6VfqBK8n?usp=sharing',
    'Анализ уязвимостей программного обеспечения / Безопасность программного кода': '1tzp-37GdJE2QxMwafa1Xzjo9ROhx7115?usp=sharing',
    'Аналитическая геометрия': '1VAUV4tf4RylUP5OVNvnV80ryQDnQ_XZp?usp=sharing',
    'Аппаратные средства вычислительной техники': '1ansxumX56Uqxix8Og5jIiZuazxpmnlZF?usp=sharing',
    'Ассемблер': '1XzROMKthQRJddrd8FxQinR_CIosKRzgH?usp=sharing',
    'Базы данных': '1EprZ4Kotpo8Jzk6MTYvTbxdp48YyqDa2?usp=sharing',
    'Безопасность жизнедеятельности': '1DM0J3p66WbhIQ_qODfruDDemJgVj-FxD?usp=sharing',
    'Бизнес-английский язык в IT': '1H1nAU8-MPX_8LpsvV8MXEVUPONqFsB2d?usp=sharing',
    'Биоинформатика': '1X0HcuLdJ1qvZvUc7-3LSYDbKlwE3MN66?usp=sharing',
    'Вариационное исчисление и оптимальное управление': '1w00xAG0EzMPsQutB8nxoOnBvH5JHc3e6?usp=sharing',
    'Введение в прикладную математику': '12IU698EbkjHKnlYrJbCteBK27stLxU9T?usp=sharing',
    'Введение в программирование': '1Dz818otaozkeXlav6eMUTWKHmNXUXdsW?usp=sharing',
    'Вредоносные программные средства': '18ygXBmo7vG3UATzRbvCR0XG_3wpc1jOp?usp=sharing',
    'Вредоносные программные средства / Компьютерные вирусы': '1fHFV-8Adh-IkqYiUkAsyyiMbukq9Nual?usp=sharing',
    'Высокопроизводительные вычисления': '1PbNwHYHE6MqiAYWLNKj6CIUW8yTStYoU?usp=sharing',
    'Вычислительные сети / Администрирование локальных вычислительных сетей': '14Bkbci0MvMBE6eZQ45CYy0fux5xcBe9m?usp=sharing',
    'Вычислительные системы': '1qe4_ONFeu8dCTQ6phjal3mFttflmqQhX?usp=sharing',
    'Геометрия': '1ssHpEKJL30DWsBZ8RhZz671-4fI3JsFr?usp=sharing',
    'Графическая визуализация и машинная графика': '1Kx5BMAZLWtIWuCO-nfXyVx5sasLkHExX?usp=sharing',
    'Деловая коммуникация': '1kzJjGjfAm1LY_jxoiwosXjO8knszlf-K?usp=sharing',
    'Дискретная математика': '1QiUfnj1LKXTA9kwefOWQ4kMb0k0wq1uM?usp=sharing',
    'Дискретная математика и математическая логика': '1cgV01E4OwiSS0NyaWhJ92d8Q02i-InqX?usp=sharing',
    'Дифференциальная геометрия': '1MiCab5GSGgETaWikiy6WZLqWlUsr7v5T?usp=sharing',
    'Дифференциальные уравнения': '1YTFF7gNuCoHqslBTSgzaoDcncxHd0bxO?usp=sharing',
    'Документоведение': '1Rq8K_nOLM3ty8FMynaS2dg84qYXKaT91?usp=sharing',
    'Дополнительные главы дискретной математики': '1E_hF7AOg3mw15nbSQVDUkpyX0Hc2fHdE?usp=sharing',
    'Дополнительные главы математического анализа': '1q8y-prvusei1-mZOHVkIE0FdqjiE88JE?usp=sharing',
    'Защита в операционных системах': '1IJWsXPERNCNi7NUu26CiAKsfdxAsq0Tj?usp=sharing',
    'Защита в операционных системах / Администрирование безопасности операционных систем': '16FlYwhvg8lBmoO4JBuO-bHZfe5q-d0N2?usp=sharing',
    'Защита информации': '1GiRBjK7txsOZw11omJno0vO3DvdluKv7?usp=sharing',
    'Защита информации / Случайные процессы': '1tVP69G4GpZtqwOEOUkU1aGkjzQomgDG7?usp=sharing',
    'Защита информации от утечки по техническим каналам': '15LVvygbrOrM-yfKWeGJlatjItiLRjB3S?usp=sharing',
    'Защита программ и данных': '1g6xaxdtWr_iQyy5ibEO1ygEGfWvR2d3J?usp=sharing',
    'Защита систем управления базами данных': '1erVIqMzCjoZZA5JxuHJlIgkMl6JEjYbE?usp=sharing',
    'Иностранный язык': '144YcoL1NCWJo07qAJToTxGmIRWJSJfN2?usp=sharing',
    'Интерфейсы периферийных устройств / Программная инженерия': '1g5MhFba199mTCodwSTTPtcyPXlm1rXgr?usp=sharing',
    'Информатика': '1xp1UU9lh-y8jXah6MhQR1pUka77_Myjm?usp=sharing',
    'Информационная безопасность': '1F4IO1hjl9bw5933JIIwk3hNS12J18ymv?usp=sharing',
    'Информационная безопасность и защита информации': '1wVK-j00vu989ZZjb1jIT_6nOjTOdc2xs?usp=sharing',
    'Информационные системы и технологии': '1FmxayBq_Q4UWh6zRTra12urIXWAryaAT?usp=sharing',
    'Информационные технологии': '1jsz1-4FaM5julmF1S_nBKrwnuQptP0dw?usp=sharing',
    'Искусственный интеллект': '1eqUot3jTvYyzHoxbz_f9ltTMExHlUOmV?usp=sharing',
    'Искусственный интеллект и логическое программирование': '14S8UuUfHV530uvzJAoPF1K63qh9utQyO?usp=sharing',
    'Исследование операций и методы оптимизации': '1qBYd-b2V14-GMnTosVilzqGuSqIeubeD?usp=sharing',
    'История': '16oN2hye2czvmBz-5qYWbmyfFypJXsWk2?usp=sharing',
    'История (история России, всеобщая история)': '1etQhEaIK6kojECpOb16wOpQl3-MMVU7M?usp=sharing',
    'История России': '1VzE1uXeHeCKPPGFB-IoeTbNEZhPng6MU?usp=sharing',
    'История и методология математики': '1t4rd8c978eo3Q4rDpEpGHPYDIGrR69o7?usp=sharing',
    'История криптографии': '1Cc0N7GyD3Mxxr8-ni3G3Lcd8Du43Afxv?usp=sharing',
    'История математики в контексте истории культуры': '1Xo1E0sAaPzWJsb-P65QKhCIKD-T_kCby?usp=sharing',
    'Квантовая кибернетика': '1GuFU_O5WPPWGrQ683iHkAirBRG5e__f-?usp=sharing',
    'Квантовые вычисления': '18x4km71GQAIjbkYJorXkwFINaXmqPLHs?usp=sharing',
    'Квантовые коммуникации': '1r8PrLsbPkh17Xvu69mml3jl9vz89_WrK?usp=sharing',
    'Кибернетика': '17ZSoUtLlmoeyUgXQPh5ZoecOPydnioLG?usp=sharing',
    'Кибернетика / Метрология, стандартизация и сертификация': '1k85ajz_0Q4yFl5uury4gbI7bj7emfpJO?usp=sharing',
    'Командная проектная работа': '1FOo72xVJBhkq1xZ-hS3bR9VXRbsx9GZo?usp=sharing',
    'Коммутация и маршрутизация': '12QNRa8b5EY2T394lM2ER_-6Fkq24IDSh?usp=sharing',
    'Компиляторы и методы трансляции': '1V17ecbmAe0L8ySUpgWWHdAuFNTeelbFg?usp=sharing',
    'Комплексный анализ': '1D-6b5SiiOXtnVRkRn1AULIxfEdR7p8Jo?usp=sharing',
    'Комплексный анализ-2': '1jvtcXVqgS6paYjOt4-9RRX9oVAYvECoX?usp=sharing',
    'Компьютерная геометрия и геометрическое моделирование': '1_7x07hRVAsRfaIV1jXJcEEeoqR_sxxuV?usp=sharing',
    'Компьютерная графика': '1kK-rVw4wJIy951YbldiPGIhQIR6HCzeS?usp=sharing',
    'Компьютерная экспертиза': '17fHkvRRZGHsVEnmb1lVi7toHa5HosSBl?usp=sharing',
    'Компьютерные сети': '1ddcWgCUYSsR2LUa1DSP5xtqc_UC_mIVa?usp=sharing',
    'Компьютерный практикум': '1sPLFlbwUkHV08rPw4_NI-lv6wbBhWm0O?usp=sharing',
    'Корпоративные информационные системы / Цифровая обработка сигналов': '1gCxUauvfWrUlOQTbO0H_Oj-B1Ic6YqkF?usp=sharing',
    'Криптографические методы защиты информации': '1vA9ihZRNC9aO284W_svYc_9zBTKCOXqb?usp=sharing',
    'Криптографические протоколы': '1Av4QHvkCreGTLyZdu8zpIxLP1p3OfkdX?usp=sharing',
    'Лямбда-исчисление': '1K7IABjcxH5CHdYAyLwxsZlcIA1cvNUDJ?usp=sharing',
    'Математическая логика': '1BFqVHDuMy9Pw5Yyr2wJzHcOd_vKDttH4?usp=sharing',
    'Математическая логика и теория алгоритмов': '1hfC-LyD4_Ks535aaOKO8ZlfosbIElTd4?usp=sharing',
    'Математическая статистика': '1ZdgHXBDhygja15jBab0VLY45iP116Ycz?usp=sharing',
    'Математические основы экономики': '1PSI0vsT_V4RgDuBHOhaLcnfvcLVtX3G6?usp=sharing',
    'Математический анализ': '19nGdkLDqrITneFKNOzfMR50CHsuyApra?usp=sharing',
    'Математическое моделирование': '1Dhf3do8tPYwG9T7ySPZxNDgeRSBW2zng?usp=sharing',
    'Математическое моделирование в естествознании': '1x36gFD_eQ8iHXg-zuBD_Lcon5l8IPN5Q?usp=sharing',
    'Математическое моделирование в естествознании / Архитектура электронно-вычислительных машин и ассемблеры': '1gzBDIW7MusOjFvTRGUs4Z6Ey6tHnB6WM?usp=sharing',
    'Математическое моделирование в экономике': '1rhIEGRYPyUuu_cyMBsCUqYQC1iSN_sQE?usp=sharing',
    'Математическое моделирование в экономике / Графическая визуализация и машинная графика': '1M8xEFChlrZ-O4rnfnSl7nPrvt19wn_cx?usp=sharing',
    'Математическое моделирование в экономике / Теория кодирования': '1h6FIIcfQNzq97nWfirq_yoLCmU-qWRbq?usp=sharing',
    'Машинное обучение': '16nxTdxViKdpjgFTwGU3n3HXu_F2u8XAr?usp=sharing',
    'Машинное обучение / Дифференциальные уравнения-2': '1Upc8wTlUCUIqSrW2qAFwUzbl9Ibi3k-8?usp=sharing',
    'Междисциплинарный семинар': '1gRiBVTyqx2M9n46g44VythmMq5j-mDze?usp=sharing',
    'Межкультурная и деловая коммуникация': '1t68TOvCnDsgwkmK-D_Ch1Z-J5htGSw1O?usp=sharing',
    'Менеджмент': '1Pan5-YAaHRxEXMdGJ7ipVA6OSyo3rOhq?usp=sharing',
    'Методология научного познания': '1iWOGroo_qc92e1InlCe8xKADZTy67YJm?usp=sharing',
    'Методы верификации': '1WFykIY0f-kEy7sAUbQE_3Db_kG9doppl?usp=sharing',
    'Методы вычислений': '1s7bAO1lS_Q_cARuamsNHSPqUYNsAT1oy?usp=sharing',
    'Методы и средства криптографической защиты информации': '17f7cbJfoFNWbe9hvvkrEcfb39Oii4jWy?usp=sharing',
    'Методы и стандарты оценки защищённости компьютерных систем': '1JKEEGtmlx-V8tf5A7Mkjk26FzwHXiFok?usp=sharing',
    'Методы оптимизации': '1XyBaLZqdd06BqQ_4H5Qa02kCgGZyJjv_?usp=sharing',
    'Метрология, стандартизация и сертификация': '1SxtMopCabUGrlzkB3e6PPTRivttcxm6t?usp=sharing',
    'Механика, основы механики сплошных сред': '1krCsQZnikfZWuQeH2ur7-T04dAIQzif4?usp=sharing',
    'Модальные и дескриптивные логики': '1HXtgNAYitpqYG-JlqvWEV8Jk9dNYunvE?usp=sharing',
    'Модели безопасности компьютерных систем': '1tdACLzmK-Om5MgciHnCliKAmO1m2LXWA?usp=sharing',
    'Моделирование социальных систем': '1rbXCFvW4KTMJfVNv0ovlJkcofBa87UZx?usp=sharing',
    'Научно-исследовательский семинар / Научно-исследовательский семинар': '1YJErFryQ8DpWxBlI4nq6sy5TWfvnFDmT?usp=sharing',
    'Научно-исследовательский семинар / Научно-практический семинар': '1y-JF9kup5kXcCTB_qVCXP_DLcqLYZFuG?usp=sharing',
    'Научно-исследовательский семинар по прикладной математике / Научно-исследовательский семинар': '1hgdUHENkuFgrXSZ10fMw6G0Q-r1f5rM2?usp=sharing',
    'Начертательная геометрия и инженерная графика': '1UwgBrRy5BiOsNRTxHfyo8krbmXnbQ2kq?usp=sharing',
    'Облачные вычисления': '1xO2t3prUUz8PUzK3Mt52APfdPZoQnNqP?usp=sharing',
    'Обработка Big Data': '1jjPDYU7imLnpyihlcHMtiWHhfmjxsYzC?usp=sharing',
    'Объектно-ориентированный дизайн': '18S9brgQRvdSDKSSxNjRgr4vlkQQWzlKt?usp=sharing',
    'Операционные системы': '1YV2nyDNpCyfDNpexlZBSKQUGGilgh2JW?usp=sharing',
    'Организационное и правовое обеспечение информационной безопасности': '13URX2WShQW-6R8P9YmEYgNm0Bt0ZVev8?usp=sharing',
    'Основные направления Data Science': '101IbiE4WicuKgAXiwePWppwU2JxfBEFy?usp=sharing',
    'Основы информационного права': '1A47kBcjpCPe0OeuMPSpa5ihFS10QBGWL?usp=sharing',
    'Основы информационной безопасности': '1-0yDh9A0mjPJ0LSiFFBn2OMUCzweKIRp?usp=sharing',
    'Основы компьютерных наук': '1oWBv6G044RRdAEzds7fCVSqx99UfxOo9?usp=sharing',
    'Основы построения защищённых баз данных': '13dJ8gz2T9M1EDrhA65dwcnnuAyv4uGbE?usp=sharing',
    'Основы построения защищённых компьютерных сетей': '1vqYk9IgrfVL8qmFQnD8w4m9SIOGrBNWp?usp=sharing',
    'Основы предпринимательства': '1O7_dPm9L6_Y6ejcw-Ad4myNe0aNhi6F7?usp=sharing',
    'Основы программирования': '1qsDVJSmN-Kwb8aKkv-vvMNz6B59Fz0pQ?usp=sharing',
    'Основы российской государственности': '1CzBHI8RTeN_huOSF2T0cP5ek6kbp7CPX?usp=sharing',
    'Основы теории управления': '1bEM5KE5uiXhCZ8GFqGvnPY6DBPZwntlX?usp=sharing',
    'Основы тестирования программного обеспечения': '1AGU8VxGXeUrtaDkBkCqv6W1W0dZvNjc5?usp=sharing',
    'Основы управления информационной безопасностью': '119aF7Yi-yL8lo7QVUeAxXnHp-C9JdK3N?usp=sharing',
    'Основы управленческой деятельности / Основы менеджмента': '1dCMfaZu0YT_DIri7TBshNmrhacr3BZTP?usp=sharing',
    'Основы управленческой деятельности / Основы теории управления': '1jdepppjNPoF-COGfBvCLIyQH_5Gu3r-V?usp=sharing',
    'Основы цифровых расследований': '19l8zFfg8pZViRdAY35kBjwDVTJ8uBAvu?usp=sharing',
    'Пакеты прикладных программ': '1z965aHUQIjDl2SW0QssaL-hZXj4CZIpP?usp=sharing',
    'Параллельные алгоритмы': '1aLjh-1xKseL3eYUe3kW6OzD_YC-QfuwY?usp=sharing',
    'Правоведение': '1joBx44oYZyafyleF6oQJw4sE0hkxeeZX?usp=sharing',
    'Правовые основы профессиональной деятельности': '1H5R913z1ngJXX-OM-Wax-jKdhRW24KXq?usp=sharing',
    'Практикум управления проектами': '1SNfohe6uRRHzy1B0CaE76wXZGL6ICMx-?usp=sharing',
    'Преддипломная практика': '1e7AWoq6j9e-dYzYftt-FUuAQJXKkN54a?usp=sharing',
    'Прикладная физическая культура и спорт': '1d-K7etEgcaTcaJ44Di7KlhyPaH7-3DOe?usp=sharing',
    'Программирование для баз данных': '1sAGtWxZWNTZ-vIiX5biLs95GYCVa_fqy?usp=sharing',
    'Программирование мобильных устройств': '1C4faJ0Q3_7uMN8Ie511qz5o5bp0jE54z?usp=sharing',
    'Программирование на C++': '1O609HnwJ_Yv5a3y4wATtMiPWfXheXIMP?usp=sharing',
    'Программирование на языке высокого уровня': '11NT10tcXphn_f8RFVNgVptSjxPMz1PZ6?usp=sharing',
    'Программирование серверных приложений': '154_ByyX4zOfdIlOwrTPkckjrKQ84RiQt?usp=sharing',
    'Программирование сетевых приложений': '1dyyQMHiKLV1hSCd_PmYN6xXME0c1kMBU?usp=sharing',
    'Программная инженерия': '1KN23qVTZO8j_cZnSrYtMXhzTlTkYc8rH?usp=sharing',
    'Программно-аппаратные средства защиты информации': '1TVINOttjdJogPJrN3HPeCsyJxb6DheJ6?usp=sharing',
    'Проектирование интеллектуальных систем': '1nSFnZ6T544vW3H_bquUa0BB-WzEkDhTw?usp=sharing',
    'Проектирование информационных систем': '1sReKoq7ND_mZRrUA7E76T9m9nSwTm4sR?usp=sharing',
    'Проектный практикум': '1WpegkiFLCppJE9sUS1zb4KhxuPYEvlGu?usp=sharing',
    'Производственная практика: научно-исследовательская работа': '1N8_nZchyfryREMpomuSqq6AUyn9oSQTB?usp=sharing',
    'Производственная практика: преддипломная практика': '1L80m23qxZnCeNVZOnD_pEdmL87glL-eO?usp=sharing',
    'Производственная практика: технологическая (проектно-технологическая) практика': '14ZjBEL8Qn5ry1C0NDkSD5lBBCgcpMG8l?usp=sharing',
    'Производственная практика: эксплуатационная практика': '1CaIkTiexZaXGNAM-QrEAVndK4X8FU8FN?usp=sharing',
    'Производственная практика: эксплуатационно-технологическая практика': '1BSIQd0Ec2VVemsT4vbou_sEevH60Pt_-?usp=sharing',
    'Психология общения': '1hJ9leX5pHTKVc9wI3ymh4ISPFPnMsMzE?usp=sharing',
    'Разработка САПР': '1S7dFnfHEC8R1nCRvtzmnFMXtCCKrtPwU?usp=sharing',
    'Разработка бизнес-приложений': '1WYcu7ROZ30pbvEjjDigf8jxbOvRQQTF4?usp=sharing',
    'Разработка бизнес-приложений (1С)': '1A6Br8UiM8zHzt7ugJf9Lwgcvw-qP0Bt0?usp=sharing',
    'Распознавание образов': '1BJwS_I2RbjWLvUtaFVHpnD9kPBQsLzz4?usp=sharing',
    'Русский язык и культура речи': '150e3TORQkl_R-hfohrdUZv4DCLBFQ9UY?usp=sharing',
    'Русский язык и культура речи / Практическая риторика': '1n8-l6SHmZOppmdAKtCVFEzrNpROLiFqO?usp=sharing',
    'Сети и системы передачи информации': '1yLE50pw-By1QEXm7v7fB21EVrtrM1d3B?usp=sharing',
    'Сети и системы телекоммуникаций': '1ck0wRSbofvf7Z7CljkAOlsASbgVjJT9S?usp=sharing',
    'Сети и телекоммуникации': '168ULmuK6oFp4TSmx_5MOtlCze_sqf_t4?usp=sharing',
    'Системное и прикладное программное обеспечение': '1IUmM0HLbcRXr97k8tlxt0EUWkPPXkQCo?usp=sharing',
    'Системное и прикладное программное обеспечение-2': '1eUZTmjmaxPnoOgMEWusrlX9TflIFlrBQ?usp=sharing',
    'Системы управления базами данных': '1Jm-L7H7aC6QyE2QBQGJ4Jp_J1F0_btkq?usp=sharing',
    'Случайные процессы': '1UTyF3LcFvN2tt9ptUkCd4CIrKHTKyikV?usp=sharing',
    'Современные методы оптимизации': '1YlehGOkkdQPFbHN7wJCQUpl6EBGireLk?usp=sharing',
    'Современные педагогические теории, системы и технологии': '1nSgmJpy_O19Sp6Ar-aT4Mk8WhXFpcnYb?usp=sharing',
    'Современные численные методы и пакеты прикладных программ': '1808Xb94VKEMgq-RE2eLSRjQL8whf-ELj?usp=sharing',
    'Социальная кибернетика': '13dBJVhyIGzfrItIQWx3JsFjEjSONXErb?usp=sharing',
    'Социальная кибернетика / Моделирование социальных систем': '1OdIc83-cz7b-G6XsLtyqximwQQECjLq5?usp=sharing',
    'Социология': '1IuYT6pFB9KT3iR-wkUXnMuyIHbxaNAI6?usp=sharing',
    'Социология / Социальная кибернетика': '1AE9zoVxrTQnWj3OgetQjHsnUzyK5LIHM?usp=sharing',
    'Социология / Социальные проблемы современного общества': '1AK8ac4e7qOMnpQDX9dJYgKPPrE8FHER3?usp=sharing',
    'Специализация': '10ekP4TewOXUITx3UTOjjnxW-xU5dsB-s?usp=sharing',
    'Специализация по прикладной математике': '1GHctrrUvxA26m3dv2raWGByUf6n8UScb?usp=sharing',
    'Специализация по прикладной математике / Специализация': '1MRFSnJJOCpS5U_R8TvJgNHbxZAN87jwz?usp=sharing',
    'Специализация по программированию / Специализация': '1-ECRjMmvCB4jXpHaamfWTmVfjQAYLCQC?usp=sharing',
    'Специализация по фундаментальной математике / Специализация по прикладной математике': '1mrb6QGvSBc29CYKSU5CTtLD-uTu25Dm_?usp=sharing',
    'Структуры и алгоритмы компьютерной обработки данных': '1ujBDAZ-RN0N6O_A9n4JjN-ppONr7d5g0?usp=sharing',
    'Суперкомпьютерные технологии / Пакеты прикладных программ': '1Z4TW94fQmdaLVCR_BiexvAjHuSg4RogX?usp=sharing',
    'Теоретико-числовые методы в криптографии': '18BO3dqA3Bl2Hz5PlWShroYt3deBR9TDP?usp=sharing',
    'Теоретическая механика': '1yPy7dZr1-5ZGP0kBumpFjDrwkJIR2N6h?usp=sharing',
    'Теория автоматов': '1Zj_iwTojCbVu-rxjibpFzbnnW4k7OEqM?usp=sharing',
    'Теория автоматов и формальных языков / Дифференциальная геометрия': '1Y0Wfz9nfACBwufj0xQIZWcPgbtqmYCqY?usp=sharing',
    'Теория алгоритмов и сложности вычислений': '1TwKvA6C2UeAJD8ZpGEdym149V3MFLBIW?usp=sharing',
    'Теория вероятностей': '1ICgHQGYHTCu0rsv7ma49VLE9mRdlEKRB?usp=sharing',
    'Теория вероятностей и математическая статистика': '1AIP4GgsXlspH_QKPsltXKDHWRkTxL8vL?usp=sharing',
    'Теория вычислимости': '14-EPzC-bxO-COClNDshvnaag8ZFtmT8B?usp=sharing',
    'Теория графов и комбинаторные алгоритмы': '1HvSDF86UUOaldBSEAsj9VFazL2k1Smr_?usp=sharing',
    'Теория игр': '1AC5XM_HKNZf-R45xR1nfNJgxt9PxzFZN?usp=sharing',
    'Теория игр и исследование операций': '1LGKtI3HeUC0VOqy3UKnh5v4pb7S81uuq?usp=sharing',
    'Теория информации': '1pPHc546gzPuRA3RELWWwYJqMBP-k0bsY?usp=sharing',
    'Теория категорий и топосы': '1Mvt8sq4wHJ3p-e1DpVdtITkDxyGHWFZ9?usp=sharing',
    'Теория систем и системный анализ': '1FSsMYITHagUDeu-Kv-0gHIskFP2tyLt3?usp=sharing',
    'Теория функций комплексного переменного': '1dCZSjVTqdXAiaUbf0VqVtrZ7usllYWLZ?usp=sharing',
    'Техническая защита информации': '1-FkpW2LEe7dYERrFif3CNCzlxr9z6dH4?usp=sharing',
    'Технологии и методы программирования': '1SJ0cLZIWyK1S34qNkod5Iyyjwo4dv4be?usp=sharing',
    'Технологии разработки программного обеспечения': '1wm75EWOdDQJzRqyzBVu0rRXSfaHBAy51?usp=sharing',
    'Топология': '1yhk9xBCHP2F5zlcYZGRUmeAXAOYm4oQM?usp=sharing',
    'Удалённый доступ и компьютерные сети': '17ON93Y_ULUS2lVgVULL3jBAoAdMyJjRf?usp=sharing',
    'Управление проектированием информационных систем': '16OC4E9opNqROG27iF3_PJzhQb90K2ztZ?usp=sharing',
    'Уравнения математической физики': '1M_CzdyEC4eH1dhIB211lQr2J6A3XF4T7?usp=sharing',
    'Учебная практика: научно-исследовательская работа (получение первичных навыков научно-исследовательской работы)': '1fB7BMxdflmoX94UyftJ3UpiwSXbBMd5j?usp=sharing',
    'Учебная практика: ознакомительная практика': '1MGU9YNbqQR1_VlA_Qa01O6h5DVzn186J?usp=sharing',
    'Учебная практика: практика по получению первичных профессиональных умений и навыков': '1KKPeliBALx6XPtBo4xe0H3H8PhkJxKAO?usp=sharing',
    'Учебная практика: практика по получению первичных профессиональных умений и навыков, в том числе первичных умений и навыков научно-исследовательской деятельности': '1ikUR2NxrbuuIwQ_zFxbwBRFneIL8jfW1?usp=sharing',
    'Учебная практика: проектная практика': '1XkmVZrQ0AOXa5V2BUGveUdI_eEhyPrLV?usp=sharing',
    'Учебная практика: технологическая (проектно-технологическая) практика': '1iwtMLNiGFY-mzhYxN2MZm3MPWuymxQbV?usp=sharing',
    'Физика': '19DWXQ3-6CsRNKj2nz3KaE7FZedXYG3AE?usp=sharing',
    'Физическая культура и спорт': '1gQMCQKU_8YjPivEwUtn0jHUEmmmAIcbh?usp=sharing',
    'Физическая культура и спорт (спортивное совершенствование)': '1lf3O8wdWxDCWb68OrslnTMGTf8B2ZQ7U?usp=sharing',
    'Философия': '1qfPgxpeLQ6G5mq1lVOG9sOEMWGelzI1c?usp=sharing',
    'Функциональное программирование / Программная инженерия': '1SAuL1nyJMwsjt5swf-isomuz6qiVUN5Q?usp=sharing',
    'Функциональный анализ': '1AwTk4tkyEjnSRS5zsHO_kyHLLwQRyuYG?usp=sharing',
    'Функциональный анализ-2': '1VhJXBHGo5y_P60XEuM2UJjHvYuCZZtZd?usp=sharing',
    'Цифровая обработка сигналов / Корпоративные информационные системы': '1H3JGapnUUs3ESCUL1HCcUovQGTgBJZST?usp=sharing',
    'Численные методы': '1YT0mmvnan29JMaMm5qJfqlCzRwt_BIwu?usp=sharing',
    'ЭВМ и периферийные устройства': '1jea4a4oWuxFTOsoZLXbNeELdeBfB5fzN?usp=sharing',
    'Экология': '1035KzsqMO_kXdJUUNo__I9MDiXh3q_SB?usp=sharing',
    'Экономика': '1VwzRjOdzEoR4IiAgVJ41d6WyvgBNFUo-?usp=sharing',
    'Экономика фирмы': '1Xl8pyKHRhD-j3lYosoJxoXCrSgqsLuUG?usp=sharing',
    'Экономическая безопасность': '12tcwRkQZOfNtEe7CWBLGCv8D9Io4df9Q?usp=sharing',
    'Электроника и схемотехника': '10u41imQhSdSPeGWt4vPl5Ow0hLpXFsMH?usp=sharing',
    'Электротехника': '1GNyrTX6-S0YBMFZid2PFia94wVnajd6w?usp=sharing',
    'Языки и методы программирования': '16pfkUpSpiIw_uLN0f8dwNYUHw3Qci6fd?usp=sharing',
    'Языки программирования': '1-HpOP0czmcAMTgE1wBXyqb1guY_Kw_Sc?usp=sharing',
  };

  static Map<String, String> listOfReductionItems = {
    'Алгоритмы анализа данных и машинное обучение / Веб-программирование': 'Алгоритмы анализа данных',
    'Алгоритмы спектрального анализа данных / Защита сетевого периметра': 'Алгоритмы спектрального анализа данных',
    'Анализ уязвимостей программного обеспечения / Безопасность программного кода': 'Анализ уязвимостей / Безопасность программного кода',
    'Вычислительные сети / Администрирование локальных вычислительных сетей': 'Вычислительные сети',
    'Защита в операционных системах / Администрирование безопасности операционных систем': 'Защита в операционных системах / Администрирование',
    'Интерфейсы периферийных устройств / Программная инженерия': 'Интерфейсы периферийных устройств',
    'Корпоративные информационные системы / Цифровая обработка сигналов': 'Корпоративные информационные системы',
    'Математическое моделирование в естествознании / Архитектура электронно-вычислительных машин и ассемблеры' : 'Математическое моделирование в естествознании / Ассемблеры',
    'Математическое моделирование в экономике / Графическая визуализация и машинная графика': 'Математическое моделирование в экономике / Графическая визуализация',
    'Научно-исследовательский семинар / Научно-исследовательский семинар': 'Научно-исследовательский семинар',
    'Научно-исследовательский семинар / Научно-практический семинар': 'Научно-практический семинар',
    'Научно-исследовательский семинар по прикладной математике / Научно-исследовательский семинар': 'Научно-исследовательский семинар по прикладной математике',
    'Производственная практика: технологическая (проектно-технологическая) практика': 'Производственная практика: технологическая практика',
    'Специализация по программированию / Специализация': 'Специализация по программированию',
    'Специализация по фундаментальной математике / Специализация по прикладной математике': 'Специализация по фундаментальной математике',
    'Учебная практика: научно-исследовательская работа (получение первичных навыков научно-исследовательской работы)': 'Учебная практика: научно-исследовательская работа',
    'Учебная практика: практика по получению первичных профессиональных умений и навыков': 'Учебная практика',
    'Учебная практика: практика по получению первичных профессиональных умений и навыков, в том числе первичных умений и навыков научно-исследовательской деятельности': 'Учебная практика: научно-исследовательская деятельность',
  };

  static Map<String, String> listOfReductionItemsForItemPage = {
    'Алгоритмы анализа данных и машинное обучение / Веб-программирование': 'Алгоритмы анализа данных',
    'Алгоритмы спектрального анализа данных / Защита сетевого периметра': 'Алгоритмы спектрального анализа данных',
    'Анализ уязвимостей программного обеспечения / Безопасность программного кода': 'Анализ уязвимостей / Безопасность программного кода',
    'Вычислительные сети / Администрирование локальных вычислительных сетей': 'Вычислительные сети',
    'Защита в операционных системах / Администрирование безопасности операционных систем': 'Защита в операционных системах / Администрирование',
    'Интерфейсы периферийных устройств / Программная инженерия': 'Интерфейсы периферийных устройств',
    'Корпоративные информационные системы / Цифровая обработка сигналов': 'Корпоративные информационные системы',
    'Математическое моделирование в естествознании / Архитектура электронно-вычислительных машин и ассемблеры' : 'Математическое моделирование в естествознании / Ассемблеры',
    'Математическое моделирование в экономике / Графическая визуализация и машинная графика': 'Математическое моделирование в экономике / Графическая визуализация',
    'Научно-исследовательский семинар / Научно-исследовательский семинар': 'Научно-исследовательский семинар',
    'Научно-исследовательский семинар / Научно-практический семинар': 'Научно-практический семинар',
    'Научно-исследовательский семинар по прикладной математике / Научно-исследовательский семинар': 'Научно-исследовательский семинар по прикладной математике',
    'Производственная практика: технологическая (проектно-технологическая) практика': 'Производственная практика: технологическая практика',
    'Теория функций комплексного переменного': 'ТФКП',
    'Специализация по программированию / Специализация': 'Специализация по программированию',
    'Специализация по фундаментальной математике / Специализация по прикладной математике': 'Специализация по фундаментальной математике',
    'Учебная практика: научно-исследовательская работа (получение первичных навыков научно-исследовательской работы)': 'Учебная практика: научно-исследовательская работа',
    'Учебная практика: практика по получению первичных профессиональных умений и навыков': 'Учебная практика',
    'Учебная практика: практика по получению первичных профессиональных умений и навыков, в том числе первичных умений и навыков научно-исследовательской деятельности': 'Учебная практика: научно-исследовательская деятельность',
  };


}

class Group {
  String name;
  int countOfSubgroups;
  Group({
    required this.name,
    required this.countOfSubgroups
  });
}
