name: applicate
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0-290.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  outline_gradient_button: ^2.0.0+1

  cupertino_icons: ^1.0.2
  webview_flutter: ^4.2.4
  flutter_webview_plugin: ^0.4.0
  shared_preferences: ^2.1.1
  flutter_svg: ^2.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/Icon_2.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/img_onboarding.png
    - assets/images/menu_fon.png
    - assets/images/img_bag.svg
    - assets/images/img_location.svg
    - assets/images/img_mail.svg
    - assets/images/img_man.svg
    - assets/images/Double_arrow.svg
    - assets/icons/back.svg
    - assets/icons/back_top.svg
    - assets/icons/semester.svg
    - assets/icons/download.svg
    - assets/img_for_items/
    - assets/img_for_teachers/
    - assets/icons/
    - assets/icons/type_of_attestation.svg
    - assets/icons/calendar.svg


  fonts:
    - family: RobotoBold
      fonts:
        - asset: assets/fonts/RobotoRomanBold.ttf
          weight: 900
