name: applicate
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0-290.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  outline_gradient_button: ^2.0.0+1

  cupertino_icons: ^1.0.2
  webview_flutter: ^2.0.14
  shared_preferences: ^2.1.1
  flutter_svg: ^2.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/img_onboarding.png
    - assets/images/img_bag.svg
    - assets/images/img_location.svg
    - assets/images/img_mail.svg
    - assets/images/img_man.svg
    - assets/images/Double_arrow.svg
    - assets/images/Man.svg
    - assets/img_for_items/admin_seti.jpg
    - assets/img_for_items/alg.jpg
    - assets/img_for_items/alg_and_geom.jpg
    - assets/img_for_items/algoritm_prog.jpg
    - assets/img_for_items/anal_geom.jpg
    - assets/img_for_items/analiz.jpg
    - assets/img_for_items/BGD.jpg
    - assets/img_for_items/books.jpg
    - assets/img_for_items/c++.jpg
    - assets/img_for_items/chis_metod.jpg
    - assets/img_for_items/cloud_vich.jpg
    - assets/img_for_items/com_proj_job.png
    - assets/img_for_items/comp_anal.jpg
    - assets/img_for_items/comp_eks.jpg
    - assets/img_for_items/compilar.jpg
    - assets/img_for_items/DB.jpg
    - assets/img_for_items/def_seti.jpg
    - assets/img_for_items/del_com.jpg
    - assets/img_for_items/dif_geom.jpg
    - assets/img_for_items/dif_ur.jpg
    - assets/img_for_items/dis_oop.jpg
    - assets/img_for_items/disc_math.jpg
    - assets/img_for_items/docs.jpg
    - assets/img_for_items/eco_def.jpg
    - assets/img_for_items/ecology.jpg
    - assets/img_for_items/electro_shema.png
    - assets/img_for_items/elertro_tech.jpg
    - assets/img_for_items/eng.jpg
    - assets/img_for_items/eng_it.jpg
    - assets/img_for_items/filosof.jpg
    - assets/img_for_items/fiz_ra.jpg
    - assets/img_for_items/funk_anal.jpg
    - assets/img_for_items/graf_vis.jpg
    - assets/img_for_items/history.jpg
    - assets/img_for_items/infor.jpg
    - assets/img_for_items/isk_int.jpg
    - assets/img_for_items/kvant_comm.jpg
    - assets/img_for_items/legal_security.jpg
    - assets/img_for_items/lyabda.jpg
    - assets/img_for_items/math_anal.jpg
    - assets/img_for_items/math_log.jpg
    - assets/img_for_items/math_model.jpg
    - assets/img_for_items/mech.jpg
    - assets/img_for_items/meneg.jpg
    - assets/img_for_items/metod_optim.jpg
    - assets/img_for_items/metod_scientist.png
    - assets/img_for_items/metrology.jpg
    - assets/img_for_items/oper_sys.jpg
    - assets/img_for_items/parralel.jpg
    - assets/img_for_items/phyzik.jpg
    - assets/img_for_items/prac_tech.jpg
    - assets/img_for_items/prak_proj_tech.jpg
    - assets/img_for_items/pravo.png
    - assets/img_for_items/prog.jpg
    - assets/img_for_items/prog_lang.jpg
    - assets/img_for_items/prog_mobile.jpg
    - assets/img_for_items/psyhology.jpg
    - assets/img_for_items/rand.jpg
    - assets/img_for_items/rasled.png
    - assets/img_for_items/rus_gos.jpg
    - assets/img_for_items/rus_lang.jpg
    - assets/img_for_items/smm.jpg
    - assets/img_for_items/soc_system.png
    - assets/img_for_items/teor_alg.jpg
    - assets/img_for_items/teor_aut.jpg
    - assets/img_for_items/teor_func_comp.jpg
    - assets/img_for_items/teor_graf.png
    - assets/img_for_items/teor_kateg.jpg
    - assets/img_for_items/teor_upr.jpg
    - assets/img_for_items/teor_ver.jpg
    - assets/img_for_items/teor_vic.jpg
    - assets/img_for_items/topology.jpg
    - assets/img_for_items/urav_math_phyz.jpg
    - assets/img_for_items/var_isch.jpg
    - assets/img_for_items/verif.jpg
    - assets/img_for_items/vich_syst.jpg
    - assets/img_for_items/vichis.jpg
    - assets/img_for_items/virus.jpg
    - assets/img_for_items/web_prog.png

  fonts:
    - family: RobotoBold
      fonts:
        - asset: assets/fonts/RobotoRomanBold.ttf
          weight: 900
